//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDrop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObavljenaDostava
    {
        public int ObavljenaDostavaId { get; set; }
        public int RutaPaketId { get; set; }
        public System.DateTime DatumVrijeme { get; set; }
        public bool Uspjesna { get; set; }
    
        public virtual RutaPaket RutaPaket { get; set; }
    }
}
