//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDrop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int RecenzijaId { get; set; }
        public int KorisnikId { get; set; }
        public int PaketId { get; set; }
        public System.DateTime DatumRecenzije { get; set; }
        public int Ocjena { get; set; }
        public string Komentar { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Paket Paket { get; set; }
    }
}
