//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDrop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaPaket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RutaPaket()
        {
            this.ObavljenaDostava = new HashSet<ObavljenaDostava>();
        }
    
        public int RutaPaketId { get; set; }
        public int RutaId { get; set; }
        public int PaketId { get; set; }
        public int Redoslijed { get; set; }
    
        public virtual Paket Paket { get; set; }
        public virtual Ruta Ruta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObavljenaDostava> ObavljenaDostava { get; set; }
    }
}
