//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDrop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            this.RutaPaket = new HashSet<RutaPaket>();
        }
    
        public int RutaId { get; set; }
        public int DronId { get; set; }
        public string Naziv { get; set; }
        public System.DateTime PlaniranPolazak { get; set; }
        public System.DateTime PlaniranPovratak { get; set; }
    
        public virtual Dron Dron { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaPaket> RutaPaket { get; set; }
    }
}
